---
- name: add gpg key
  rpm_key:
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi
- name: install remi repository
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
- name: change repository status
  ini_file:
    path: /etc/yum.repos.d/remi.repo
    section: remi
    option: enabled
    value: "{{ '1' if repo_remi_enabled else '0' }}"
    mode: "0644"
